### PR TITLE
change public file path for virtual console view

### PR DESCRIPTION
**Pull request by banrui**

### CODE REVIEW

**Comment by banrui** [comment]
Hi, please confirm my pull request. Because we cannot confirm virtual console view when I start Sinatra.

**Comment by satoryu** [comment]
@banrui out of curiosity, could you please tell me why this PR is needed?

**Comment by banrui** [comment]
@satoryu When I booted try-roma by readme procedure, I cannot see "/" root page. So I modified it.

**Comment by satoryu** [comment]
I have confirmed that your PR works as we expected. Thanks :+1:

**Pull request merged**
